# D2D (Die-to-Die) 配置文件

# D2D 特定配置
D2D_ENABLED: true
NUM_DIES: 2
D2D_LAYOUT: "VERTICAL"  # 布局方式：HORIZONTAL(水平) 或 VERTICAL(垂直)


# D2D 延迟配置 (cycles)
D2D_AR_LATENCY: 10  # 地址读通道延迟
D2D_R_LATENCY: 8    # 读数据通道延迟
D2D_AW_LATENCY: 10  # 地址写通道延迟
D2D_W_LATENCY: 2    # 写数据通道延迟
D2D_B_LATENCY: 8    # 写响应通道延迟
D2D_DBID_LATENCY: 5 # DBID 信号延迟
D2D_MAX_OUTSTANDING: 16  # 最大未完成事务数

# D2D 带宽控制
D2D_DATA_BW_LIMIT: 64  # D2D数据通道带宽限制 (与其他IP接口格式一致)
D2D_RN_BW_LIMIT: 128    # D2D RN 带宽限制 (GB/s)
D2D_SN_BW_LIMIT: 128    # D2D SN 带宽限制 (GB/s)

# D2D 资源管理配置
# D2D_RN 跟踪器配置 (类似GDMA)
D2D_RN_R_TRACKER_OSTD: 48   # D2D RN 读跟踪器 OSTD
D2D_RN_W_TRACKER_OSTD: 48   # D2D RN 写跟踪器 OSTD
D2D_RN_RDB_SIZE: 192        # D2D RN 读databuffer大小
D2D_RN_WDB_SIZE: 192        # D2D RN 写databuffer大小

# D2D_SN 跟踪器配置 (类似DDR)
D2D_SN_R_TRACKER_OSTD: 48   # D2D SN 读跟踪器 OSTD
D2D_SN_W_TRACKER_OSTD: 48   # D2D SN 写跟踪器 OSTD
D2D_SN_RDB_SIZE: 192        # D2D SN 读databuffer大小
D2D_SN_WDB_SIZE: 192        # D2D SN 写databuffer大小

# D2D 接口位置列表 (网络初始化需要)
D2D_RN_SEND_POSITION_LIST: [36, 37, 38, 39]  # D2D RN接口位置 (Die0边界发送位置)
D2D_SN_SEND_POSITION_LIST: [32, 33, 34, 35]  # D2D SN接口位置 (Die0边界接收位置)