# D2D (Die-to-Die) 5x4拓扑配置文件
# 每个Die使用5x4 CrossRing拓扑，支持20个逻辑节点

# 网络拓扑参数
NUM_NODE: 40  # 物理节点数：考虑node_map映射后最大位置是39
NUM_ROW: 5    # 逻辑拓扑行数
NUM_COL: 4    # 逻辑拓扑列数
NUM_IP: 20    # IP数量：每个Die有20个逻辑节点

# 简化的IP配置（适应5x4拓扑）
NUM_RN: 10    # 减少RN数量
NUM_SN: 10    # 减少SN数量
NUM_DDR: 4    # 每个Die 4个DDR
NUM_L2M: 4    # 每个Die 4个L2M
NUM_SDMA: 4   # 每个Die 4个SDMA
NUM_GDMA: 4   # 每个Die 4个GDMA
NUM_CDMA: 4   # 每个Die 4个CDMA

# 基本参数
FLIT_SIZE: 128
SLICE_PER_LINK: 7
BURST: 4
NETWORK_FREQUENCY: 2

# FIFO 深度配置
RB_IN_FIFO_DEPTH: 8
RB_OUT_FIFO_DEPTH: 8
IQ_OUT_FIFO_DEPTH_HORIZONTAL: 6
IQ_OUT_FIFO_DEPTH_VERTICAL: 6
IQ_OUT_FIFO_DEPTH_EQ: 6
EQ_IN_FIFO_DEPTH: 8
IQ_CH_FIFO_DEPTH: 8
EQ_CH_FIFO_DEPTH: 8

# IP 频率变换 FIFO 深度
IP_L2H_FIFO_DEPTH: 3
IP_H2L_H_FIFO_DEPTH: 2
IP_H2L_L_FIFO_DEPTH: 2

# ITag 配置
ITag_TRIGGER_Th_H: 100
ITag_TRIGGER_Th_V: 100
ITag_MAX_Num_H: 1
ITag_MAX_Num_V: 1
RB_ONLY_TAG_NUM_HORIZONTAL: 2
RB_ONLY_TAG_NUM_VERTICAL: 3

# 跟踪器配置（简化）
RN_R_TRACKER_OSTD: 16
RN_W_TRACKER_OSTD: 16
RN_RDB_SIZE: 64
RN_WDB_SIZE: 64
SN_DDR_R_TRACKER_OSTD: 16
SN_DDR_W_TRACKER_OSTD: 16
SN_L2M_R_TRACKER_OSTD: 16
SN_L2M_W_TRACKER_OSTD: 16
SN_DDR_RDB_SIZE: 64
SN_DDR_WDB_SIZE: 64
SN_L2M_RDB_SIZE: 64
SN_L2M_WDB_SIZE: 64

# 带宽限制 (GB/s)
GDMA_BW_LIMIT: 128
SDMA_BW_LIMIT: 128
CDMA_BW_LIMIT: 128
DDR_BW_LIMIT: 128
L2M_BW_LIMIT: 128

# 延迟配置 (cycles)
DDR_R_LATENCY: 100
DDR_R_LATENCY_VAR: 10
DDR_W_LATENCY: 100
L2M_R_LATENCY: 20
L2M_W_LATENCY: 20
SN_TRACKER_RELEASE_LATENCY: 50

# ETag 配置
TL_Etag_T1_UE_MAX: 2
TL_Etag_T2_UE_MAX: 1
TR_Etag_T2_UE_MAX: 1
TU_Etag_T1_UE_MAX: 2
TU_Etag_T2_UE_MAX: 1
TD_Etag_T2_UE_MAX: 1
ETag_BOTHSIDE_UPGRADE: 0

# DMA 读写间隔
GDMA_RW_GAP: 0
SDMA_RW_GAP: 0

# 其他功能开关
ENABLE_CROSSPOINT_CONFLICT_CHECK: true
CROSSRING_VERSION: "V2"
ENABLE_IN_ORDER_EJECTION: false
IN_ORDER_EJECTION_PAIRS: []

# 性能阈值配置
TGT_TRAFFIC_TO_HOG_BW_RATE_THRESH: 1.8
DMA_DEADLOCK_THD: 10000

# D2D 特定配置
D2D_ENABLED: true
NUM_DIES: 2

# D2D 延迟配置 (cycles)
D2D_AR_LATENCY: 10  # 地址读通道延迟
D2D_R_LATENCY: 8    # 读数据通道延迟
D2D_AW_LATENCY: 10  # 地址写通道延迟
D2D_W_LATENCY: 2    # 写数据通道延迟
D2D_B_LATENCY: 8    # 写响应通道延迟
D2D_DBID_LATENCY: 5 # DBID 信号延迟
D2D_MAX_OUTSTANDING: 16  # 最大未完成事务数

# IP位置映射（基于node_map映射的物理位置）
# 源节点映射：node % 4 + 4 + (node // 4) * 8
# 目标节点映射：node % 4 + (node // 4) * 8

# GDMA位置（逻辑节点0-3 -> 物理位置4-7）
GDMA_SEND_POSITION_LIST: [4, 5, 6, 7]

# SDMA位置（逻辑节点4-7 -> 物理位置12-15） 
SDMA_SEND_POSITION_LIST: [12, 13, 14, 15]

# CDMA位置（逻辑节点8-11 -> 物理位置20-23）
CDMA_SEND_POSITION_LIST: [20, 21, 22, 23]

# DDR位置（逻辑节点0-3 -> 物理位置0-3）
DDR_SEND_POSITION_LIST: [0, 1, 2, 3]

# L2M位置（逻辑节点4-7 -> 物理位置8-11）
L2M_SEND_POSITION_LIST: [8, 9, 10, 11]

# IP类型列表
CH_NAME_LIST: ["gdma", "sdma", "cdma", "ddr", "l2m"]