# D2D坐标模式配置文件
# 坐标系统：左下角为原点(0,0)，x=列，y=行

D2D_ENABLED: true
NUM_DIES: 4

# Die物理布局配置
D2D_LAYOUT:
  coordinate_system: "cartesian_bottom_left"  # 明确坐标系
  dies:
    0:
      position: [0, 0]      # Die在系统中的位置 [x, y]
      topology: "5x4"       # 5行4列
      description: "左下Die"
    1:
      position: [1, 0]      # 右下
      topology: "5x4"
      description: "右下Die"
    2:
      position: [0, 1]      # 左上
      topology: "10x4"      # 不同拓扑尺寸
      description: "左上Die"
    3:
      position: [1, 1]      # 右上
      topology: "10x4"
      description: "右上Die"

# D2D连接配置（坐标模式）
D2D_CONNECTIONS:
  mode: "coordinate"        # 使用坐标模式

  # 精确的坐标对配置
  # 格式: [源Die, [源x,源y], 目标Die, [目标x,目标y]]
  pairs:
    # Die0 ↔ Die1 (水平连接)
    - [0, [3, 1], 1, [0, 1]]    # Die0的RN(3,1) ↔ Die1的SN(0,1)
    - [0, [3, 2], 1, [0, 2]]    # Die0的SN(3,2) ↔ Die1的RN(0,2)
    - [0, [3, 3], 1, [0, 3]]    # Die0的RN(3,3) ↔ Die1的SN(0,3)
    - [0, [3, 4], 1, [0, 4]]    # Die0的SN(3,4) ↔ Die1的RN(0,4)

    # Die0 ↔ Die2 (垂直连接)
    - [0, [0, 4], 2, [0, 0]]    # Die0顶部 ↔ Die2底部
    - [0, [1, 4], 2, [1, 0]]
    - [0, [2, 4], 2, [2, 0]]
    - [0, [3, 4], 2, [3, 0]]

    # Die1 ↔ Die3 (垂直连接)
    - [1, [0, 4], 3, [0, 0]]    # Die1顶部 ↔ Die3底部
    - [1, [1, 4], 3, [1, 0]]
    - [1, [2, 4], 3, [2, 0]]
    - [1, [3, 4], 3, [3, 0]]

    # Die2 ↔ Die3 (水平连接，不同拓扑尺寸)
    - [2, [3, 1], 3, [0, 1]]    # 自动处理拓扑尺寸差异
    - [2, [3, 3], 3, [0, 3]]
    - [2, [3, 5], 3, [0, 5]]
    - [2, [3, 7], 3, [0, 7]]

# D2D AXI通道配置
D2D_AXI_CONFIG:
  AR_LATENCY: 5      # Address Read latency
  AW_LATENCY: 3      # Address Write latency
  W_LATENCY: 1       # Write Data latency
  R_LATENCY: 5       # Read Data latency
  B_LATENCY: 3       # Write Response latency

# D2D资源配置
D2D_RESOURCE_CONFIG:
  SN_TRACKER_CAPACITY:
    "ro": 16          # Read Outstanding trackers
    "share": 32       # Shared (Write) trackers

  RN_TRACKER_CAPACITY:
    "read": 16        # Read trackers
    "write": 32       # Write trackers

  BUFFER_CAPACITY:
    "sn_wdb": 64      # SN Write Data Buffer
    "rn_wdb": 64      # RN Write Data Buffer
    "rn_rdb": 64      # RN Read Data Buffer

# 基础网络参数
NETWORK_FREQUENCY: 1000000000   # 1GHz
FLIT_SIZE: 64                   # 64 bytes
BURST: 8                        # Default burst length