# D2D (Die-to-Die) 4-Die 配置文件

# D2D 特定配置
D2D_ENABLED: true
NUM_DIES: 4

# 4-Die节点配置 (新的配置驱动方式)
# 布局: Die2 - Die3
#      |     |
#      Die1 - Die0
D2D_DIE_CONFIG:
  0:
    topology: "5x4"              
    connections:
      left: # 连接到左侧的Die 1
        connect_die: 1              # left边主要连接到Die 1
        d2d_nodes: [1, 2, 3]        # 左边：第1,2,3个位置（从上到下）
        node_to_die_mapping:
          1: 2  # 节点1(最上边)连接到对角Die 2
          2: 1  # 节点2连接到相邻Die 1
          3: 1  # 节点3连接到相邻Die 1
      top: # 连接到上方的Die 3
        connect_die: 3              # top边主要连接到Die 3
        d2d_nodes: [0, 1, 2]        # 上边：第0,1,2个位置（从左到右）
        node_to_die_mapping:
          0: 2  # 节点0(最左边)连接到对角Die 2
          1: 3  # 节点1连接到相邻Die 3
          2: 3  # 节点2连接到相邻Die 3
  1:
    topology: "4x5"              
    connections:
      right: # 连接到右侧的Die 0
        connect_die: 0              # right边主要连接到Die 0
        d2d_nodes: [1, 2, 3]         # 右边：第1,2,3个位置（从上到下）
        node_to_die_mapping:
          1: 3  # 节点1(最上边)连接到对角Die 3
          2: 0  # 节点2连接到相邻Die 0
          3: 0  # 节点3连接到相邻Die 0
      top: # 连接到上方的Die 2
        connect_die: 2              # top边主要连接到Die 2
        d2d_nodes: [0, 1, 2]         # 上边：第0,1,2个位置（从左到右）
        node_to_die_mapping:
          0: 2  # 节点0(最左边)连接到相邻Die 2
          1: 2  # 节点1连接到相邻Die 2
          2: 3  # 节点2连接到对角Die 3
  2:
    topology: "5x4"             
    connections:
      bottom: # 连接到下方的Die 1
        connect_die: 1              # bottom边主要连接到Die 1
        d2d_nodes: [0, 1, 2]          # 下边：第0,1,2个位置（从左到右）
        node_to_die_mapping:
          0: 1  # 节点0(最左边)连接到相邻Die 1
          1: 1  # 节点1连接到相邻Die 1
          2: 0  # 节点2连接到对角Die 0
      right: # 连接到右侧的Die 3
        connect_die: 3              # right边主要连接到Die 3
        d2d_nodes: [1, 2, 3]        # 右边：第1,2,3个位置（从上到下）
        node_to_die_mapping:
          1: 3  # 节点1(最上边)连接到相邻Die 3
          2: 3  # 节点2连接到相邻Die 3
          3: 0  # 节点3连接到对角Die 0
  3:
    topology: "5x4"              
    connections:
      left: # 连接到左侧的Die 2
        connect_die: 2              # left边主要连接到Die 2
        d2d_nodes: [1, 2, 3]         # 左边：第1,2,3个位置（从上到下）
        node_to_die_mapping:
          1: 2  # 节点1(最上边)连接到相邻Die 2
          2: 2  # 节点2连接到相邻Die 2
          3: 1  # 节点3连接到对角Die 1
      bottom: # 连接到下方的Die 0
        connect_die: 0              # bottom边主要连接到Die 0
        d2d_nodes: [0, 1, 2]          # 下边：第0,1,2个位置（从左到右）
        node_to_die_mapping:
          0: 1  # 节点0(最左边)连接到对角Die 1
          1: 0  # 节点1连接到相邻Die 0
          2: 0  # 节点2连接到相邻Die 0


# 多跳路由配置
D2D_MULTI_HOP_ENABLED: true
D2D_ROUTING_ALGORITHM: "shortest_path"  # shortest_path, load_balance

# D2D 延迟配置 (cycles) - 保持不变
D2D_AR_LATENCY: 10  # 地址读通道延迟
D2D_R_LATENCY: 10   # 读数据通道延迟
D2D_AW_LATENCY: 10  # 地址写通道延迟
D2D_W_LATENCY: 10   # 写数据通道延迟
D2D_B_LATENCY: 10   # 写响应通道延迟
D2D_DBID_LATENCY: 10 # DBID 信号延迟
D2D_MAX_OUTSTANDING: 16  # 最大未完成事务数

# D2D 带宽控制 - 保持不变
D2D_DATA_BW_LIMIT: 64   # D2D数据通道带宽限制
D2D_RN_BW_LIMIT: 128    # D2D RN 带宽限制 (GB/s)
D2D_SN_BW_LIMIT: 128    # D2D SN 带宽限制 (GB/s)

# D2D 资源管理配置 - 保持不变
# D2D_RN 跟踪器配置
D2D_RN_R_TRACKER_OSTD: 48   # D2D RN 读跟踪器 OSTD
D2D_RN_W_TRACKER_OSTD: 48   # D2D RN 写跟踪器 OSTD
D2D_RN_RDB_SIZE: 192        # D2D RN 读databuffer大小
D2D_RN_WDB_SIZE: 192        # D2D RN 写databuffer大小

# D2D_SN 跟踪器配置
D2D_SN_R_TRACKER_OSTD: 48   # D2D SN 读跟踪器 OSTD
D2D_SN_W_TRACKER_OSTD: 48   # D2D SN 写跟踪器 OSTD
D2D_SN_RDB_SIZE: 192        # D2D SN 读databuffer大小
D2D_SN_WDB_SIZE: 192        # D2D SN 写databuffer大小