# D2D (Die-to-Die) 4-Die 配置文件

# D2D 特定配置
D2D_ENABLED: true
NUM_DIES: 4

# 基本网络参数
FLIT_SIZE: 128
SLICE_PER_LINK_HORIZONTAL: 8
SLICE_PER_LINK_VERTICAL: 8
BURST: 4
NETWORK_FREQUENCY: 2

# Die的XY坐标布局（左下角为原点）
# 布局: Die2 - Die3
#      |     |
#      Die1 - Die0
DIE_POSITIONS:
  0: [1, 0]  # Die0在右下角
  1: [0, 0]  # Die1在左下角
  2: [0, 1]  # Die2在左上角
  3: [1, 1]  # Die3在右上角

# 每个Die的拓扑配置
DIE_TOPOLOGIES:
  0: "5x4"  # Die0使用5x4拓扑
  1: "4x5"  # Die1使用4x5拓扑
  2: "5x4"  # Die2使用5x4拓扑
  3: "4x5"  # Die3使用4x5拓扑

# D2D互联配置（单向配置，系统自动生成双向连接）
# 格式: [源Die, 源物理节点, 目标Die, 目标物理节点]
D2D_CONNECTIONS:
  # 水平连接（底部）
  - [0, 12, 1, 9]    # Die0左侧 <-> Die1右侧
  - [0, 16, 1, 14]

  # 水平连接（顶部）
  - [2, 3, 3, 5]    # Die2右侧 <-> Die3左侧
  - [2, 7, 3, 10]

  # 垂直连接（左侧）
  - [1, 0, 2, 17]   # Die1顶部 <-> Die2底部
  - [1, 1, 2, 18]

  # 垂直连接（右侧）
  - [0, 1, 3, 18]   # Die0顶部 <-> Die3底部
  - [0, 2, 3, 19]

  # 对角连接（可选）
  - [0, 4, 2, 11]   # Die0 <-> Die2 对角
  - [0, 8, 2, 15]   # Die0 <-> Die2 对角
  
  - [1, 2, 3, 16]   # Die1 <-> Die3 对角
  - [1, 3, 3, 17]   # Die1 <-> Die3 对角


# 多跳路由配置
D2D_MULTI_HOP_ENABLED: true
D2D_ROUTING_ALGORITHM: "shortest_path"  # shortest_path, load_balance

# D2D 延迟配置 (cycles) - 保持不变
D2D_AR_LATENCY: 10  # 地址读通道延迟
D2D_R_LATENCY: 10   # 读数据通道延迟
D2D_AW_LATENCY: 10  # 地址写通道延迟
D2D_W_LATENCY: 10   # 写数据通道延迟
D2D_B_LATENCY: 10   # 写响应通道延迟

# D2D 带宽控制
D2D_RN_BW_LIMIT: 128    # D2D RN 带宽限制 (GB/s)
D2D_SN_BW_LIMIT: 128    # D2D SN 带宽限制 (GB/s)

# D2D 资源管理配置
# D2D_RN 配置
D2D_RN_RDB_SIZE: 512        # D2D RN 读databuffer大小
D2D_RN_WDB_SIZE: 512        # D2D RN 写databuffer大小
D2D_RN_R_TRACKER_OSTD: auto # = D2D_RN_RDB_SIZE / BURST
D2D_RN_W_TRACKER_OSTD: auto # = D2D_RN_WDB_SIZE / BURST

# D2D_SN 配置
D2D_SN_RDB_SIZE: 512        # D2D SN 读databuffer大小
D2D_SN_WDB_SIZE: 512        # D2D SN 写databuffer大小
D2D_SN_R_TRACKER_OSTD: auto # = D2D_SN_RDB_SIZE / BURST
D2D_SN_W_TRACKER_OSTD: auto # = D2D_SN_WDB_SIZE / BURST