# D2D (Die-to-Die) 4-Die 配置文件

# D2D 特定配置
D2D_ENABLED: true
NUM_DIES: 4

# 4-Die节点配置 (新的配置驱动方式)
D2D_DIE_CONFIG:
  0:
    num_row: 5
    num_col: 4
    connections:
      left: {die: 1, d2d_nodes: [1, 2, 3]}        # 左边：第1,2,3个位置（从上到下）
      top: {die: 3, d2d_nodes: [0, 1, 2]}       # 上边：第0,1,2个位置（从左到右）
  1:
    num_row: 5
    num_col: 4
    connections:
      right: {die: 0, d2d_nodes: [1, 2, 3]}         # 右边：第1,2,3个位置（从上到下）
      top: {die: 2, d2d_nodes: [0, 1, 2]}       # 下边：第0,1,2个位置（从左到右）
  2:
    num_row: 5
    num_col: 4
    connections:
      bottom: {die: 1, d2d_nodes: [0, 1, 2]}          # 下边：第0,1,2个位置（从左到右）
      right: {die: 3, d2d_nodes: [1, 2, 3]}        # 右边：第1,2,3个位置（从上到下）
  3:
    num_row: 5
    num_col: 4
    connections:
      left: {die: 2, d2d_nodes: [1, 2, 3]}         # 左边：第1,2,3个位置（从上到下）
      bottom: {die: 0, d2d_nodes: [0, 1, 2]}          # 上边：第0,1,2个位置（从左到右）


# 多跳路由配置
D2D_MULTI_HOP_ENABLED: true
D2D_ROUTING_ALGORITHM: "shortest_path"  # shortest_path, load_balance

# D2D 延迟配置 (cycles) - 保持不变
D2D_AR_LATENCY: 10  # 地址读通道延迟
D2D_R_LATENCY: 10   # 读数据通道延迟
D2D_AW_LATENCY: 10  # 地址写通道延迟
D2D_W_LATENCY: 10   # 写数据通道延迟
D2D_B_LATENCY: 10   # 写响应通道延迟
D2D_DBID_LATENCY: 10 # DBID 信号延迟
D2D_MAX_OUTSTANDING: 16  # 最大未完成事务数

# D2D 带宽控制 - 保持不变
D2D_DATA_BW_LIMIT: 64   # D2D数据通道带宽限制
D2D_RN_BW_LIMIT: 128    # D2D RN 带宽限制 (GB/s)
D2D_SN_BW_LIMIT: 128    # D2D SN 带宽限制 (GB/s)

# D2D 资源管理配置 - 保持不变
# D2D_RN 跟踪器配置
D2D_RN_R_TRACKER_OSTD: 48   # D2D RN 读跟踪器 OSTD
D2D_RN_W_TRACKER_OSTD: 48   # D2D RN 写跟踪器 OSTD
D2D_RN_RDB_SIZE: 192        # D2D RN 读databuffer大小
D2D_RN_WDB_SIZE: 192        # D2D RN 写databuffer大小

# D2D_SN 跟踪器配置
D2D_SN_R_TRACKER_OSTD: 48   # D2D SN 读跟踪器 OSTD
D2D_SN_W_TRACKER_OSTD: 48   # D2D SN 写跟踪器 OSTD
D2D_SN_RDB_SIZE: 192        # D2D SN 读databuffer大小
D2D_SN_WDB_SIZE: 192        # D2D SN 写databuffer大小