# 5x4 拓扑配置 (40节点, SG2262)
TOPO_TYPE: "5x4"  # 格式 AxB，自动计算拓扑参数


# 基本参数
FLIT_SIZE: 128
SLICE_PER_LINK_HORIZONTAL: 8
SLICE_PER_LINK_VERTICAL: 8
BURST: 4
NETWORK_FREQUENCY: 2

# ========== 新的资源配置结构 ==========
# 主配置：数据缓冲区大小
RN_RDB_SIZE: 256      # RN读数据缓冲区
RN_WDB_SIZE: 256      # RN写数据缓冲区
SN_DDR_RDB_SIZE: 256  # SN DDR读数据缓冲区
SN_DDR_WDB_SIZE: 256  # SN DDR写数据缓冲区
SN_L2M_RDB_SIZE: 256  # SN L2M读数据缓冲区
SN_L2M_WDB_SIZE: 256  # SN L2M写数据缓冲区

# 次要配置：跟踪器数量（自动计算：databuffer_size / BURST）
RN_R_TRACKER_OSTD: auto    # = RN_RDB_SIZE / BURST 
RN_W_TRACKER_OSTD: auto    # = RN_WDB_SIZE / BURST 
SN_DDR_R_TRACKER_OSTD: auto # = SN_DDR_RDB_SIZE / BURST 
SN_DDR_W_TRACKER_OSTD: auto # = SN_DDR_WDB_SIZE / BURST 
SN_L2M_R_TRACKER_OSTD: auto # = SN_L2M_RDB_SIZE / BURST 
SN_L2M_W_TRACKER_OSTD: auto # = SN_L2M_WDB_SIZE / BURST 

# 资源模式配置
UNIFIED_RW_TRACKER: false   # true=读写共享资源池，false=读写分离

# 延迟配置 (原始值)
DDR_R_LATENCY: 40
DDR_R_LATENCY_VAR: 0
DDR_W_LATENCY: 0
L2M_R_LATENCY: 12
L2M_W_LATENCY: 16
SN_TRACKER_RELEASE_LATENCY: 40

# FIFO 深度配置
IQ_CH_FIFO_DEPTH: 4
EQ_CH_FIFO_DEPTH: 4
IQ_OUT_FIFO_DEPTH_HORIZONTAL: 4
IQ_OUT_FIFO_DEPTH_VERTICAL: 4
IQ_OUT_FIFO_DEPTH_EQ: 4
RB_OUT_FIFO_DEPTH: 4
# RB_IN_FIFO_DEPTH: 16
# EQ_IN_FIFO_DEPTH: 16
RB_IN_FIFO_DEPTH: 8
EQ_IN_FIFO_DEPTH: 8

# ETag 配置
# TL_Etag_T2_UE_MAX: 8
# TL_Etag_T1_UE_MAX: 15
# TR_Etag_T2_UE_MAX: 12
# TU_Etag_T2_UE_MAX: 8
# TU_Etag_T1_UE_MAX: 15
# TD_Etag_T2_UE_MAX: 12

TL_Etag_T2_UE_MAX: 4
TL_Etag_T1_UE_MAX: 7
TR_Etag_T2_UE_MAX: 6
TU_Etag_T2_UE_MAX: 4
TU_Etag_T1_UE_MAX: 7
TD_Etag_T2_UE_MAX: 6

# TL_Etag_T2_UE_MAX: 0
# TL_Etag_T1_UE_MAX: 3
# TR_Etag_T2_UE_MAX: 3
# TU_Etag_T2_UE_MAX: 0
# TU_Etag_T1_UE_MAX: 3
# TD_Etag_T2_UE_MAX: 0

# ITag 配置
ITag_TRIGGER_Th_H: 80
ITag_TRIGGER_Th_V: 80
ITag_MAX_Num_H: 1
ITag_MAX_Num_V: 1

# 其他配置
ETag_BOTHSIDE_UPGRADE: 0
GDMA_RW_GAP: .inf  # numpy.inf
SDMA_RW_GAP: .inf  # numpy.inf


# 通道规格
CHANNEL_SPEC:
  gdma: 2
  ddr: 2

# 带宽限制 (GB/s) - 注释掉表示无限制
GDMA_BW_LIMIT: 128
SDMA_BW_LIMIT: 128
CDMA_BW_LIMIT: 128
DDR_BW_LIMIT: 128
L2M_BW_LIMIT: 128

# 功能开关
CROSSRING_VERSION: "V1"
IN_ORDER_EJECTION_PAIRS: []
ENABLE_CROSSPOINT_CONFLICT_CHECK: 0
ORDERING_PRESERVATION_MODE: 1  # 0=不保序, 1=单侧下环(TL/TU), 2=双侧下环(白名单)
ORDERING_GRANULARITY: 1  # 0=IP层级, 1=节点层级
# 需要保序的包类型 (REQ/RSP/DATA)
IN_ORDER_PACKET_CATEGORIES:
  - "REQ"    # 只有REQ类型需要保序
  - "RSP"
  - "DATA"

# 双侧下环方向配置 - 5x4拓扑 (20节点: 0-19, 布局: 行0: 0-3, 行1: 4-7, 行2: 8-11, 行3: 12-15, 行4: 16-19)
TL_ALLOWED_SOURCE_NODES: [2, 3, 6, 7, 10, 11, 14, 15, 18, 19]  
TR_ALLOWED_SOURCE_NODES: [0, 1, 4, 5, 8, 9, 12, 13, 16, 17]    
TU_ALLOWED_SOURCE_NODES: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]      
TD_ALLOWED_SOURCE_NODES: [0, 1, 2, 3, 4, 5, 6, 7 ] 

# IP 频率变换 FIFO 深度 (使用默认值)
IP_L2H_FIFO_DEPTH: 3
IP_H2L_H_FIFO_DEPTH: 2
IP_H2L_L_FIFO_DEPTH: 2

# 标签配置 (仅在 base_model_v2/network_v2 中生效，base_model/d2d_model 中无效)
RB_ONLY_TAG_NUM_HORIZONTAL: 2
RB_ONLY_TAG_NUM_VERTICAL: 3

arbitration:
  # 全局默认仲裁器类型
  default:
    type: "round_robin"
#       type: "islip"
#       algorithm: "lqf"  # Longest Queue First
#       iterations: 2
#       weight_strategy: "queue_length"