# 12x12 拓扑配置 (288节点)
TOPO_TYPE: "12x12"

# 网络拓扑参数
NUM_COL: 12
NUM_NODE: 288  # 12 * 12 * 2
NUM_ROW: 24    # 12 * 2
NUM_IP: 144    # 12 * 12

# 基本参数
FLIT_SIZE: 128
SLICE_PER_LINK_HORIZONTAL: 6
SLICE_PER_LINK_VERTICAL: 6
BURST: 4
NETWORK_FREQUENCY: 2

# 跟踪器配置
RN_R_TRACKER_OSTD: 64
RN_W_TRACKER_OSTD: 64
RN_RDB_SIZE: auto  # RN_R_TRACKER_OSTD * BURST
RN_WDB_SIZE: auto  # RN_W_TRACKER_OSTD * BURST
SN_DDR_R_TRACKER_OSTD: 96
SN_DDR_W_TRACKER_OSTD: 96
SN_L2M_R_TRACKER_OSTD: 96
SN_L2M_W_TRACKER_OSTD: 48
SN_DDR_RDB_SIZE: auto  # SN_DDR_R_TRACKER_OSTD * BURST
SN_DDR_WDB_SIZE: auto  # SN_DDR_W_TRACKER_OSTD * BURST
SN_L2M_RDB_SIZE: auto  # SN_L2M_R_TRACKER_OSTD * BURST
SN_L2M_WDB_SIZE: auto  # SN_L2M_W_TRACKER_OSTD * BURST

# 延迟配置 (原始值)
DDR_R_LATENCY: 100
DDR_W_LATENCY: 40
L2M_R_LATENCY: 12
L2M_W_LATENCY: 16
SN_TRACKER_RELEASE_LATENCY: 40

# FIFO 深度配置
IQ_CH_FIFO_DEPTH: 10
EQ_CH_FIFO_DEPTH: 10
IQ_OUT_FIFO_DEPTH_HORIZONTAL: 8
IQ_OUT_FIFO_DEPTH_VERTICAL: 8
IQ_OUT_FIFO_DEPTH_EQ: 8
RB_OUT_FIFO_DEPTH: 8

# ETag 配置
TL_Etag_T2_UE_MAX: 8
TL_Etag_T1_UE_MAX: 15
TR_Etag_T2_UE_MAX: 12
RB_IN_FIFO_DEPTH: 16
TU_Etag_T2_UE_MAX: 8
TU_Etag_T1_UE_MAX: 15
TD_Etag_T2_UE_MAX: 12
EQ_IN_FIFO_DEPTH: 16

# ITag 配置
ITag_TRIGGER_Th_H: 80
ITag_TRIGGER_Th_V: 80
ITag_MAX_Num_H: 1
ITag_MAX_Num_V: 1

# 其他配置
ETag_BOTHSIDE_UPGRADE: 0
GDMA_RW_GAP: .inf  # numpy.inf
SDMA_RW_GAP: .inf  # numpy.inf

# 通道规格
CHANNEL_SPEC:
  gdma: 2
  sdma: 0
  cdma: 0
  ddr: 2
  l2m: 0

# 默认带宽配置
GDMA_BW_LIMIT: 128
SDMA_BW_LIMIT: 128
CDMA_BW_LIMIT: 128
DDR_BW_LIMIT: 128
L2M_BW_LIMIT: 128

# 其他功能开关
ENABLE_CROSSPOINT_CONFLICT_CHECK: 0
ENABLE_IN_ORDER_EJECTION: 0
CROSSRING_VERSION: "V1"
IN_ORDER_EJECTION_PAIRS: []
# 需要保序的包类型 (REQ/RSP/DATA)
IN_ORDER_PACKET_CATEGORIES:
  - "REQ"    # 只有REQ类型需要保序

# IP 频率变换 FIFO 深度 (使用默认值)
IP_L2H_FIFO_DEPTH: 3
IP_H2L_H_FIFO_DEPTH: 4
IP_H2L_L_FIFO_DEPTH: 4

# 标签配置 (使用默认值)
RB_ONLY_TAG_NUM_HORIZONTAL: 2
RB_ONLY_TAG_NUM_VERTICAL: 3

# 其他从默认配置继承的参数
NUM_DDR: 32
NUM_L2M: 32
NUM_SDMA: 32
NUM_GDMA: 32
NUM_RN: 32
NUM_SN: 32
NUM_CDMA: 3