# 3x3 拓扑配置 (18节点)
TOPO_TYPE: "3x3"

# 基本参数
FLIT_SIZE: 128
SLICE_PER_LINK_HORIZONTAL: 8
SLICE_PER_LINK_VERTICAL: 8
BURST: 4
NETWORK_FREQUENCY: 2

# ========== 资源配置 ==========
# 主配置：数据缓冲区大小
RN_RDB_SIZE: 512      # RN读数据缓冲区
RN_WDB_SIZE: 128      # RN写数据缓冲区
SN_DDR_RDB_SIZE: 128  # SN DDR读数据缓冲区
SN_DDR_WDB_SIZE: 64  # SN DDR写数据缓冲区
SN_L2M_RDB_SIZE: 256  # SN L2M读数据缓冲区
SN_L2M_WDB_SIZE: 256  # SN L2M写数据缓冲区

# 次要配置：跟踪器数量（自动计算：databuffer_size / BURST）
RN_R_TRACKER_OSTD: auto    # = RN_RDB_SIZE / BURST 
RN_W_TRACKER_OSTD: auto    # = RN_WDB_SIZE / BURST 
SN_DDR_R_TRACKER_OSTD: auto # = SN_DDR_RDB_SIZE / BURST 
SN_DDR_W_TRACKER_OSTD: auto # = SN_DDR_WDB_SIZE / BURST 
SN_L2M_R_TRACKER_OSTD: auto # = SN_L2M_RDB_SIZE / BURST 
SN_L2M_W_TRACKER_OSTD: auto # = SN_L2M_WDB_SIZE / BURST 

# 资源模式配置
UNIFIED_RW_TRACKER: false   # true=读写共享资源池，false=读写分离

# 延迟配置 (原始值)
DDR_R_LATENCY: 155
DDR_W_LATENCY: 16
L2M_R_LATENCY: 12
L2M_W_LATENCY: 16
DDR_R_LATENCY_VAR: 0

# FIFO 深度配置
IQ_CH_FIFO_DEPTH: 8
EQ_CH_FIFO_DEPTH: 8
IQ_OUT_FIFO_DEPTH_HORIZONTAL: 8
IQ_OUT_FIFO_DEPTH_VERTICAL: 8
IQ_OUT_FIFO_DEPTH_EQ: 8
RB_OUT_FIFO_DEPTH: 8

# ETag 配置
TL_Etag_T2_UE_MAX: 8
TL_Etag_T1_UE_MAX: 12
TR_Etag_T2_UE_MAX: 12
RB_IN_FIFO_DEPTH: 16
TU_Etag_T2_UE_MAX: 8
TU_Etag_T1_UE_MAX: 12
TD_Etag_T2_UE_MAX: 12
EQ_IN_FIFO_DEPTH: 16

# ITag 配置
ITag_TRIGGER_Th_H: 80
ITag_TRIGGER_Th_V: 80
ITag_MAX_Num_H: 1
ITag_MAX_Num_V: 1

# 其他配置
GDMA_RW_GAP: .inf  # numpy.inf
SDMA_RW_GAP: .inf  # numpy.inf

# 通道规格
CHANNEL_SPEC:
  gdma: 2
  sdma: 2
  ddr: 2
  l2m: 2

# 带宽限制 (GB/s) - 注释掉表示无限制
# DDR_BW_LIMIT: 19.2  # 76.8 / 4
# L2M_BW_LIMIT: .inf

# 其他功能开关
ENABLE_CROSSPOINT_CONFLICT_CHECK: 0
ENABLE_IN_ORDER_EJECTION: 0
CROSSRING_VERSION: "V1"
IN_ORDER_EJECTION_PAIRS: []
# 需要保序的包类型 (REQ/RSP/DATA)
IN_ORDER_PACKET_CATEGORIES:
  - "REQ"    # 只有REQ类型需要保序

# 方向控制配置 - 3x3拓扑 (9节点: 0-8, 布局: 行0: 0-2, 行1: 3-5, 行2: 6-8)
TL_ALLOWED_SOURCE_NODES: [2, 5, 8]          # 向左：右半部(列2)
TR_ALLOWED_SOURCE_NODES: [0, 1, 3, 4, 6, 7]  # 向右：左半部(列0,1)
TU_ALLOWED_SOURCE_NODES: [6, 7, 8]          # 向上：下半部(行2)
TD_ALLOWED_SOURCE_NODES: [0, 1, 2, 3, 4, 5]  # 向下：上半部(行0,1)

# IP 频率变换 FIFO 深度 (使用默认值)
IP_L2H_FIFO_DEPTH: 3
IP_H2L_H_FIFO_DEPTH: 2
IP_H2L_L_FIFO_DEPTH: 2

# 标签配置 (仅在 base_model_v2/network_v2 中生效，base_model/d2d_model 中无效)
RB_ONLY_TAG_NUM_HORIZONTAL: 2
RB_ONLY_TAG_NUM_VERTICAL: 3

# DMA 配置 (使用默认值)
GDMA_BW_LIMIT: 128
SDMA_BW_LIMIT: 128
CDMA_BW_LIMIT: 128
DDR_BW_LIMIT: 128
L2M_BW_LIMIT: 128
SN_TRACKER_RELEASE_LATENCY: 40
ETag_BOTHSIDE_UPGRADE: 0